export const todos = [
  "Buy milk",
  "Call mom",
  "Send emails",
  "Exercise for 30 minutes",
  "Grocery shopping",
  "Pay bills",
  "Read a book",
  "Water the plants",
  "Plan weekend trip",
  "Walk the dog",
  "Write a blog post",
  "Clean the kitchen",
  "Update resume",
  "Dentist appointment",
  "Schedule haircut",
  "Declutter closet",
  "Meditate for 10 minutes",
  "Watch a TED talk",
  "Organize desk",
  "Check the mailbox",
  "Research vacation spots",
  "Set a budget",
  "Take out the trash",
  "Fix the leaky faucet",
  "Review meeting notes",
  "Meal prep for the week",
  "Buy a birthday gift",
  "Call the plumber",
  "Change light bulbs",
  "File taxes",
  "Sort laundry",
  "Create a playlist",
  "Buy new shoes",
  "Schedule doctor's visit",
  "Send thank you cards",
  "Update software",
  "Practice guitar",
  "Water the garden",
  "Read the news",
  "Set up a meeting",
  "Renew library books",
  "Buy a new phone case",
  "Paint the bedroom",
  "Review project proposal",
  "Check stock prices",
  "Plan dinner menu",
  "Call a friend",
  "Clean the bathroom",
  "Check car oil",
  "Research new appliances",
  "Register for a class",
  "Backup files",
  "Study for exam",
  "Iron clothes",
  "Buy groceries for the week",
  "Write a to-do list",
  "Pay credit card bill",
  "Arrange a playdate",
  "Fix the roof",
  "Plant flowers in the garden",
  "Make a dentist appointment",
  "Call the cable company",
  "Organize the garage",
  "Buy a gift for anniversary",
  "Book a flight",
  "Check email",
  "Install new software update",
  "Write a thank you note",
  "Schedule a meeting with the team",
  "Change air filters",
  "Take a walk in the park",
  "Visit the library",
  "Call the insurance company",
  "Clean out the fridge",
  "Set up a savings account",
  "Write a journal entry",
  "Learn a new recipe",
  "Buy a new laptop bag",
  "Call the electrician",
  "Research a new hobby",
  "Check tire pressure",
  "Water the indoor plants",
  "Replace batteries in smoke detectors",
  "Create a workout plan",
  "Write a poem",
  "Organize the pantry",
  "Check for software updates",
  "Buy a new coffee maker",
  "Make a dentist appointment for kids",
  "Plan a surprise party",
  "Call the pest control",
  "Review monthly expenses",
  "Clean the garage",
  "Write a love letter",
  "Schedule a haircut for kids",
  "Check the weather forecast",
  "Update social media profiles",
  "Buy a new book",
  "Call the vet for pet checkup",
  "Create a shopping list",
  "Plan a movie night",
  "Set up a home budget",
  "Write a short story",
  "Organize the attic",
  "Check for flight deals",
  "Water the outdoor plants",
];
